### ISSUE TITLE
Add ChaneLog

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-loader#11]
I see `0.0.4` → `1.0.3` update, but can’t find what was changes in a simple form.

I think all open source projects must have ChangeLog. A lot of people agree: https://keepachangelog.com/ru/1.0.0/

There are two forms for ChangeLog:
* `CHANGELOG.md` file
* GitHub Releases (just create git tag for the release and fill changes [in Releases page](https://github.com/usmanyunusov/webpack-webmanifest-plugin/releases))

**Comment by usmanyunusov** [comment]
Added GitHub Releases - https://github.com/usmanyunusov/webpack-webmanifest-loader/releases
