### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-loader#12]
Since you do not have a plugin anymore, it is a good time to rename project.

Also, if the project will have `-loader` ending, we can use `use: 'X-loader'` in webpack config without `import`.

**Comment by usmanyunusov** [comment]
The project name was changed in [release 2.0.1](https://github.com/usmanyunusov/webpack-webmanifest-loader/commit/ef5e9d41bdfa85f2f9fc5c526fbd301b3f84c81c)
